spring:
  application:
    name: auth
  datasource:
    url: jdbc:mariadb://localhost:3307/fashion
    username: test
    password: 1234
    driverClassName: org.mariadb.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8001