spring:
  application:
    name: config
  profiles:
    native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dev-hjkim/msa_toy_config
          skipSslValidation: true
server:
  port: ${PORT:8088}