spring:
  application:
    name: gw
#  config:
#    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/v1/auth/**
          filters:
            - RewritePath=/v1/auth/?(?<segment>.*), /$\{segment}

server:
  port: ${PORT:8000}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
