spring:
  application:
    name: gw
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/v1/auth/**
          filters:
            - RewritePath=/v1/auth/?(?<segment>.*), /$\{segment}

server:
  port: ${PORT:8000}

eureka:
  client:
    serviceUrl:
      defaultZone: https://celebrity-eureka.herokuapp.com/eureka
