spring:
  application:
    name: eureka
#  config:
#    import: "optional:configserver:http://localhost:8088"

server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/