spring:
  application:
    name: eureka
  cloud:
    config:
      enabled: false


server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://celebrity-eureka.herokuapp.com/eureka