server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v1/auth/**
          filters:
            - RewritePath=/v1/auth/?(?<segment>.*), /$\{segment}